name: Deploy to XServer
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Build Project
        run: |
          mkdir -p src/assets/img  # ← これだけ！
          npm ci
          npm run build

      - name: Deploy (SFTP.json完全一致)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_KEY }}
          SSH_CMD_ARGS: "-o ConnectTimeout=60 -o ServerAliveInterval=10 -o StrictHostKeyChecking=no"
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: "sv16201.xserver.jp"
          REMOTE_USER: "xs655858"
          REMOTE_PORT: "10022"
          TARGET: "/home/xs655858/web-tera-design.com/public_html/demosite/wp-content/themes/demosite"
          EXCLUDE: |
            .vscode
            .index.html
            .src
            node_modules
            .git
            .DS_Store
            README.md
            package.json
            package-lock.json
            gulpfile.js
            .gitignore
